import random

recent_prescripts = [] # This will store recently generated prescripts to avoid immediate repetition

triggers = [
    "After finishing a drink",
    "Before answering the next direct question",
    "When someone nearby mentions a location",
    "After hearing your own name",
    "If a door opens unexpectedly",
    "Before sitting down again",
    "When your phone lights up",
    "After passing a reflective surface",
    "If two voices overlap",
    "Before touching your next object",
    "After checking the time",
    "When someone laughs nearby",
    "If a room becomes silent",
    "Before crossing a doorway",
    "After someone repeats a word",
    "When you notice movement behind glass",
    "After hearing metal touch another surface",
    "Before writing your next sentence",
    "When someone asks for clarification",
    "After adjusting your posture",
    "Before opening anything closed",
    "When footsteps stop behind you",
    "After standing from a chair",
    "If someone interrupts themselves",
    "Before looking outside",
    "After a task ends earlier than expected",
    "When another person checks the time",
    "Before apologizing",
    "After hearing distant machinery",
    "When an object drops nearby",
    "Before accepting an offer",
    "After noticing a repeated sound",
    "When someone lowers their voice",
    "Before finishing your next thought",
    "After a brief hesitation",
    "When entering a brighter room",
    "Before moving an object again",
    "After hearing your own footsteps",
    "When someone changes topic abruptly",
    "Before choosing where to stand",
    "When a clock hand moves noticeably",
    "After mishearing a word",
    "Before placing something down",
    "When a light flickers once",
    "After someone repeats your gesture",
    "Before turning toward a sound",
    "When the temperature feels different suddenly",
    "After hearing a digital notification tone",
    "When someone clears their throat",
    "Before responding to your own question",
    "When your reflection seems delayed",
    "After realizing you've lost track of time",
    "Before completing a repeated motion",
    "When two sounds synchronize briefly",
    "After someone hesitates to speak",

    "When a conversation ends without resolution",
    "After noticing you have been watched",
    "Before forming a clear opinion",
    "When someone smiles without reason",
    "After a sound you cannot identify",
    "Before the silence becomes comfortable",
    "When two people make eye contact near you",
    "After an object is returned to its original position",
    "When you recognize a pattern for the second time",
    "Before a task you have postponed",
    "When someone leaves without saying why",
    "After you catch yourself performing naturally",
    "When a window reflects an unfamiliar angle",
    "Before resuming something interrupted",
    "When a nearby device emits heat you can feel",
    "After being addressed in the wrong tone",
    "When a room contains one more person than you expected",

    "When someone finishes a sentence you already knew the end of",
    "After realizing you have been agreeing without listening",
    "Before a question you know will not be answered honestly",
    "When the ambient noise drops by half",
    "After touching something warmer than expected",
    "When someone looks at you before speaking to someone else",
    "Before you are asked to confirm something obvious",
    "When a familiar smell arrives without a source",
    "After nodding more than twice in a row",
    "When no one in the room is moving",
    "Before you are about to be interrupted",
    "When the light changes without a visible cause",
    "After finishing something that felt longer than it was",
    "When a word you were about to use is said by someone else",
    "Before entering a space you have not fully mapped",
    "When someone near you stops pretending to be busy",
    "After a pause that was longer than either party intended",
    "When you realize you have been standing at an angle",
    "Before receiving news you have already prepared for",
    "When a door closes more softly than expected",
    "After performing an action you cannot account for",
    "When someone refers to a version of events you do not share",
    "Before the last person leaves a room",
    "When something arrives earlier than promised",
    "After being watched without acknowledgment",
    "When you are the only one who heard a sound",
    "Before accepting something as finished",
    "When a familiar routine deviates by one step",
    "After the third time you have checked the same thing",
    "When someone describes you accurately without knowing you",
    "Before the room returns to what it was",
    "When someone uses a word you were just thinking",
    "After a task that required no thought at all",
    "When you are the first to notice something is wrong",
    "Before occupying a space someone recently left",
    "When a conversation resumes as though it was never paused",
    "After making a decision without remembering the moment of decision",
    "When two people agree too quickly",
    "Before you are seen doing something ordinary",
    "When a shadow arrives before the object casting it",
]

actions_1 = [
    "change the subject without warning",
    "touch the nearest cold surface",
    "step aside once before continuing",
    "delay your answer by two breaths",
    "watch the nearest moving person silently",
    "rotate one nearby object slightly",
    "close and reopen something available",
    "repeat the last noun silently",
    "look toward the farthest visible corner",
    "lower your voice unexpectedly",
    "fold something once",
    "pause until another sound occurs",
    "move one object farther than needed",
    "look behind the speaker briefly",
    "stand still for four seconds",
    "answer with fewer words than necessary",
    "ask a harmless question first",
    "ignore your first response impulse",
    "place one hand behind your back",
    "finish the next motion slowly",
    "adjust an object that does not require adjustment",
    "briefly face the wrong direction",
    "hold your next object longer than needed",
    "remove one word from your reply",
    "look downward before speaking",
    "tap the nearest surface once",
    "interrupt your own first sentence",
    "count silently before continuing",
    "lift something and return it unchanged",
    "wait until someone shifts position",
    "tilt your head as if reconsidering something unseen",
    "touch your sleeve once without reason",
    "draw a small unseen shape on a surface",
    "repeat a simple motion with intent",
    "focus briefly on an unimportant detail",
    "take half a step without direction",
    "press two fingers together and release them",
    "inhale sharply through the nose before exhaling slowly",
    "move your eyes in the direction opposite your thought",
    "pause mid-motion and resume as if nothing occurred",
    "shift your weight twice before choosing a stance",
    "trace the perimeter of an invisible edge",
    "rest both hands still for three breaths",
    "look at your hands as if they belonged to someone else",
    "adjust something already aligned",
    "murmur a word you do not intend to use",

    "remain still until the feeling passes",
    "reposition yourself as though correcting an error",
    "observe the nearest threshold without crossing it",
    "let your hands fall to your sides before continuing",
    "briefly pretend you were already standing here",
    "withdraw one step as if completing an earlier movement",
    "avoid the word that arrives first",
    "maintain your current expression without confirming it",
    "continue the previous motion without its original purpose",
    "slow your pace to match an invisible rhythm",
    "address the nearest object with your full attention",
    "occupy exactly as much space as required",
    "delay the gesture until it no longer feels necessary",
    "become briefly unlocatable in your own attention",
    "allow your eyes to pass over rather than land",

    "hold your current position as though it were intentional",
    "allow your attention to rest on the least significant detail",
    "perform the action as though demonstrating it for someone behind you",
    "resist the correction that arrives immediately after",
    "complete the motion without confirming it was necessary",
    "move with the speed of someone who has already been told",
    "occupy the pause as though it belongs to you",
    "allow the thought to surface without following it",
    "continue as though your presence here was authorized",
    "treat the nearest object as a known quantity",
    "release the tension from one hand without moving the other",
    "finish the sentence inside your head and offer a shorter version",
    "approach the nearest boundary without crossing it",
    "let your gaze land without intent",
    "hold the breath exactly as long as the discomfort requires",
    "arrange your hands as though expecting to be photographed",
    "continue with the certainty of someone who has already failed here",
    "redirect your attention toward a less urgent surface",
    "perform the next action as a rehearsal of the one that follows",
    "allow the moment to be witnessed without confirming the witness",
    "slow your movement to the speed of someone not being watched",
    "close the distance by exactly one increment",
    "address the silence as though it asked you something",
    "decide, without evidence, that this is the correct position",
    "become aware of your own breathing without altering it",
]

actions_2 = [
    "then mirror the seventh movement you notice",
    "then avoid explaining why",
    "then abandon the original topic",
    "then continue as though interrupted earlier",
    "then leave one sentence unfinished",
    "then do not repair the silence",
    "then look away before hearing the reply",
    "then behave as if it was accidental",
    "then answer only after another sound occurs",
    "then refuse internally to repeat it",
    "then wait for posture to change nearby",
    "then avoid touching the same object again",
    "then continue as if expected",
    "then deny hesitation through tone alone",
    "then change volume once before finishing",
    "then face slightly away",
    "then end the exchange first",
    "then avoid the obvious word",
    "then delay departure",
    "then leave one detail incorrect",
    "then pretend no adjustment was made",
    "then shift attention elsewhere immediately",
    "then continue without acknowledgment",
    "then allow the pause to remain visible",
    "then interrupt your own conclusion",
    "then stop one action early",
    "then resume at normal pace",
    "then do not repeat the same posture",
    "then wait before looking back",
    "then continue with deliberate calm",

    "then lower your gaze before anyone reacts",
    "then remain where you are for one extra second",
    "then allow someone else to move first",
    "then continue speaking more quietly than before",
    "then do not correct what now feels slightly wrong",
    "then behave as if you had already decided this earlier",
    "then leave the nearest object untouched",
    "then continue before certainty returns",
    "then allow the interruption to remain unresolved",
    "then ignore the most obvious follow-up",
    "then do not revisit the earlier motion",
    "then wait until another voice appears",
    "then finish before the expected moment",
    "then answer as though nothing changed",
    "then withdraw attention without warning",
    "then continue facing the wrong direction briefly",
    "then do not acknowledge the nearest reaction",
    "then hold the final word slightly longer",
    "then pause before returning to ordinary pace",
    "then leave before the exchange settles",
    "then avoid the most direct response",

    "then allow one harmless misunderstanding to remain",
    "then continue as though timing had been corrected",
    "then avoid returning to the original object",
    "then accept the silence without filling it",
    "then end the movement before it feels complete",
    "then wait until someone else adjusts position",
    "then continue without recovering the earlier tone",
    "then behave as if the delay was required",
    "then allow the unfinished detail to persist",
    "then shift your posture only once more",
    "then continue before anyone comments",
    "then look at nothing directly for a moment",
    "then refuse to clarify immediately",
    "then allow the previous sentence to stand alone",
    "then continue only after hearing another movement",
    "then avoid symmetry in your next action",
    "then lower one hand slowly",
    "then let the first response remain unanswered",
    "then continue without confirming intention",
    "then delay the next obvious action",

    "then speak as though recalling a forgotten script",
    "then maintain eye contact until context shifts",
    "then turn away before understanding why",
    "then behave as if nothing had been said",
    "then wait for something familiar to happen again",
    "then allow meaning to decay naturally",
    "then continue only once the irregularity feels ordinary",
    "then stop exactly halfway through the next instinct",
    "then mirror your earlier pace imperfectly",
    "then resume only when silence seems aware of itself",
    "then adjust expression to match an unseen rhythm",
    "then dismiss the thought without confirming its source",
    "then let the interruption become part of the act",
    "then move as if instructed by another memory",
    "then still your body, but not your thought",
    "then restart a motion exactly once more",

    "then do not register what just changed",
    "then perform the next action as a different version of yourself",
    "then treat the discomfort as a signal, not a problem",
    "then continue as though the decision was made earlier by someone else",
    "then allow the thought to complete itself without you",
    "then return to a pace that belongs to someone less aware",
    "then behave as if this moment was already in the record",
    "then let the sequence resume without your permission",
    "then continue toward the original position as if nothing diverted you",
    "then do not confirm whether anyone noticed",
    "then release the breath as though it carried a count",
    "then accept that the interaction has already been categorized",
    "then leave the corrected version out of reach",
    "then continue as if the body had already decided",
    "then allow the next action to arrive without intent",

    "then allow the unfinished motion to stand as a complete one",
    "then behave as though the intention was always secondary",
    "then continue without locating the source of the relief",
    "then proceed as if the error has already been accounted for",
    "then do not name what changed in your posture",
    "then return to ordinary motion as though this was a detour",
    "then hold the next object as if it might be examined later",
    "then speak as if the previous version of yourself had already explained",
    "then perform the next sequence in a key no one has agreed upon",
    "then behave as if someone else has already corrected for this",
    "then allow the next moment to arrive without preparation",
    "then continue as if the room's arrangement had been approved",
    "then do not look for confirmation that this was necessary",
    "then proceed without checking whether the instruction was yours",
    "then let the silence take the shape of what was not said",
    "then continue toward the next expected behavior without acceleration",
    "then allow the completed action to be forgotten before it is questioned",
    "then move as if you are being returned to your starting position",
    "then carry out the next gesture as a translation of this one",
    "then do not register that something was resolved",
    "then continue as if the person watching has already turned away",
    "then release ownership of the previous moment entirely",
    "then allow the exit to feel like it was suggested by the room",
    "then proceed as though this were the second time, not the first",
    "then continue without verifying that the action was yours to take",
]

extra_layers = [
    "before anyone notices",
    "without revisiting the earlier choice",
    "unless another sound interrupts first",
    "before the next person finishes speaking",
    "without returning to the original subject",
    "unless eye contact breaks first",
    "before checking whether anyone reacted",
    "without correcting yourself afterward",
    "unless interrupted by a second question",
    "before another object moves nearby",
    "without altering your expression",
    "before anyone asks again",
    "unless another voice intervenes",
    "before changing position",
    "without confirming intention",
    "before the next expected moment",
    "unless someone else reacts first",

    "before questioning your own hesitation",
    "without showing recognition",
    "unless another pattern repeats",
    "before confirming what you observed",
    "without clarifying your reason",
    "before acknowledging repetition",
    "unless sound returns to normal first",
    "before anyone resumes activity",
    "without tracing it back consciously",

    "before the pattern loses its shape",
    "without deciding whether it was correct",
    "unless someone names what just happened",
    "before memory assigns it a category",
    "without measuring the distance it created",
    "unless it resolves on its own",
    "before your expression catches up",
    "without locating the original reason",
    "unless the room shifts attention first",
    "before you've confirmed your position",

    "before the action acquires a name",
    "without confirming the source of the instruction",
    "unless the sequence has already been completed elsewhere",
    "before the body registers the decision as voluntary",
    "without identifying which part of you gave the signal",
    "unless the next action renders this one unnecessary",
    "before anyone else has oriented toward it",
    "without knowing whether this was the correct response",
    "unless the weight of it shifts on its own",
    "before the moment is stored as memory",
    "without assigning it to the correct day",
    "unless someone has already begun the same sequence",
    "before your expression becomes legible",
    "without knowing if this is still part of the same instruction",
    "unless the sensation is already fading",
    "before it becomes possible to explain",
    "without registering the scale of it",
    "unless the room has already moved past it",
    "before you can decide whether you chose it",
    "without knowing how many times this has already occurred",


]

endings = [
    ".",
    ".",
    ".",
    ", and continue normally.",
    ", then resume ordinary behavior.",
    ", without comment.",
    ", and do not revisit it.",
    ", as if this resolved something.",
    ", before anyone objects.",
    ", while keeping your pace unchanged.",
    ", and allow the silence to remain.",
    ", without acknowledging the change.",
    ", and do not account for the time it took.",
    ", as though the sequence had always ended here.",
    ", before the cause becomes traceable.",
    ", and allow it to be misread.",
    ", without marking it as complete.",
    ", as if this were a correction, not an addition.",
    ", and leave the purpose unstated.",
    ", without confirming it was directed at anyone.",
    ", as though the room requested it.",
    ", and do not follow it further.",
    ", before it acquires the weight of habit.",
    ", as if someone had already done this and you are simply repeating the result.",
    ", without deciding whether it succeeded.",
    ", and let the next moment inherit nothing from this one.",
    ", as though this were the version that will not be remembered.",
    ", without arriving at a reason.",
    ", and proceed as though the record reflects something slightly different.",
    ", as if this concluded something that began before you were present.",
    ", without establishing that it was yours to perform.",
    ", and treat the absence of response as confirmation.",
    ", before the action becomes indistinguishable from its repetition.",
    ", as though the instruction had already been carried out by someone else.",
    ", without requiring the moment to mean anything.",
    ", and leave one detail available for misinterpretation.",
    ", as though this were a formality observed by people who have forgotten its origin.",
    ", without looking for the seam.",
]

manual_rare = [
    "After a meal, change the subject to your favorite food and mirror the movements of the seventh person you see, then pretend this interaction never occurred.",
    "Before entering your next room, touch the wall first and avoid using the first sentence that comes to mind.",
    "When someone thanks you, delay your reply until another sound occurs and answer as though they had spoken earlier.",
    "After hearing laughter, observe the nearest reflective surface before speaking again.",
    "Carry an unnecessary object briefly, then leave it somewhere visible but unjustified.",
    "When someone repeats themselves, answer only the second version and lower your voice halfway through.",
    "Pause before opening your next message and look away once before reading it.",
    "At your next opportunity to sit, remain standing until another person shifts position.",
    "When offered a simple choice, internally reject both options before answering aloud.",
    "After crossing a doorway, check behind you without stopping.",

    "When someone greets you by name, pause as if uncertain it was meant for you, then answer using a question instead.",
    "After passing through an empty hallway, turn once as though searching for a previous sound.",
    "If you notice a repeated phrase, echo it under your breath and end on a different word.",
    "Before opening a new page or tab, lower your gaze and imagine you’ve already read it.",
    "At your next conversation’s midpoint, change your posture as though responding to a silent prompt.",
    "When your reflection meets your eyes, pretend you arrived one moment late.",
    "After ending a message, hover as if reconsidering the tone but do not edit it.",
    "Before picking up something important, touch a meaningless object first.",
    "When you hear overlapping voices, decide privately which one spoke truth.",
    "Following your next sigh, behave as if the air still weighs on your shoulders.",

    "When something is almost finished, leave one step undone and continue as though completion was never the goal.",
    "After someone explains something clearly, nod once and then begin the explanation again internally in different terms.",
    "Before your next deliberate action, pause long enough to forget why you began it.",
    "When you are introduced to someone, register their name once and do not use it again in that encounter.",
    "If you notice you are performing ease, allow one visible hesitation before the performance continues.",
    "After passing a group in conversation, decide privately what they were discussing and let that version stand.",
    "When you enter a room already occupied, briefly behave as though you arrived before everyone else.",
    "If someone asks what you are thinking, offer the second thought, not the first.",
    "Before sitting near a stranger, calculate the minimum acceptable distance and choose one seat beyond it.",
    "When a task completes without difficulty, treat the ease as suspicious and proceed with slightly more care.",

    "Before your next long task, arrange the objects nearby as though preparing for someone else's use, then proceed as the someone else.",
    "When you catch yourself thinking in lists, abandon the structure mid-item and allow the remainder to arrive in whatever order it chooses.",
    "After a silence you did not create, take partial credit for it.",
    "When someone nearby is confident, quietly identify the one detail they have not considered.",
    "Before sending something you have revised more than twice, remove one change and leave one error as evidence of process.",
    "After entering a building you have been in before, note one thing that has changed and one thing that could not have stayed the same but did.",
    "When you feel observed, continue your current task with the small adjustments of someone who has nothing to adjust.",
    "Before accepting the first available seat, consider whether it is the seat a person waiting to be found would choose.",
    "After finishing a conversation, reconstruct its opening line from memory and compare it to what was actually said.",
    "When an object is returned to you, briefly treat it as unfamiliar.",
    "After being asked a question you know the answer to, take one breath longer than the answer requires.",
    "When someone is clearly about to make a mistake, decide in advance whether your role in this room is to say so.",
    "Before your next departure from any space, identify the last thing you will see, and let it be something unremarkable.",
    "When you realize you have been comfortable for a long time, do not adjust anything, but make a record of it.",
    "After laughter fades before it should, note who moved on first.",
]

environmental_actions = [
    "briefly stop when passing a shadow",
    "face the nearest corner before continuing",
    "wait until a separate sound interrupts the silence",
    "change direction once before resuming",
    "observe the nearest light source without comment",
    "cross only after adjusting your pace",
    "pause near the nearest threshold",
    "step back before proceeding",
    "delay movement until another object shifts",
    "continue only after lowering your gaze"
]

speech_actions = [
    "replace one expected word with another harmless one",
    "begin speaking slightly too late",
    "interrupt your own answer deliberately",
    "repeat only the middle part of a sentence internally",
    "allow a pause where one is unnecessary",
    "answer as if another question had been asked first",
    "avoid naming the obvious subject",
    "change tone midway through the sentence",
    "omit one explanation entirely",
    "finish speaking earlier than intended"
]

social_actions = [
    "mirror one posture briefly",
    "stand where you were not originally heading",
    "let another person move first without reason",
    "look away before receiving the response",
    "change your orientation during conversation",
    "leave one interaction unfinished",
    "delay acknowledgment slightly",
    "allow silence to remain visible",
    "withdraw attention before expected",
    "pretend certainty where none is required"
]

internal_actions = [
    "consider whether this has already occurred",
    "translate the last thought into a gesture",
    "name silently what you cannot describe",
    "remind yourself of a rule no one gave you",
    "resist the urge to confirm your presence",
    "decide to forget one recent observation",
    "mentally assign meaning to the nearest object",
    "rehearse an apology you will not deliver",
]

observational_actions = [
    "catalog the room's exits before continuing",
    "determine which object would outlast all others here",
    "note which person has spoken least",
    "locate the source of the ambient sound",
    "count the visible light sources without moving",
    "decide which surface would best record what happened here",
    "identify who has changed position most recently",
    "register the arrangement of objects as though it may shift",
    "observe which person seems most prepared to leave",
    "notice the smallest moving thing in the room",
]

temporal_actions = [
    "treat the current moment as already past",
    "behave as though this event was scheduled in advance",
    "continue as if five minutes have already elapsed",
    "respond as though the question was asked earlier",
    "occupy the present moment only partially",
    "act as though you have performed this before today",
    "carry out the motion as a form of remembering",
    "delay long enough that the action becomes its own cause",
]

perceptual_actions = [
    "treat what you see as a description of what was there",
    "register the sound as arriving from a slightly different direction",
    "decide the texture of the nearest surface without touching it",
    "process the current image as a copy of an earlier one",
    "hear the most recent sentence as though it was spoken in a different register",
    "assign the ambient smell to a place you have not been in years",
    "treat the current light as the memory of a brighter room",
    "read the nearest text as though it were addressed to a previous version of you",
    "receive the instruction as though it arrived through an intermediary",
    "experience the temperature as evidence of a decision made earlier",
]

relational_actions = [
    "behave as though the nearest person arrived here before you and has been waiting",
    "treat the current group as if one member has not yet been introduced",
    "speak as though your role here has not yet been confirmed",
    "hold the position of someone who has been asked to observe but not to intervene",
    "continue as if you owe the room one more unspoken courtesy",
    "treat the most recent speaker as a relay for a message sent earlier",
    "carry out your next action as if it has already been agreed upon",
    "maintain the distance of someone who was once much closer",
    "proceed as though the expectation was set before you arrived",
    "respond to the subtext without acknowledging the text",
]

all_first_actions = actions_1 + environmental_actions + social_actions + speech_actions + internal_actions + observational_actions + temporal_actions + perceptual_actions + relational_actions # This combines all the first actions into one list for easier random selection
def generate_prescript(): # This function generates a new prescript by randomly selecting a trigger, two actions, and an optional extra layer, while ensuring that the same prescript is not repeated too frequently.
    global recent_prescripts

    if random.random() < 0.12:
        text = random.choice(manual_rare)
    else:
        while True:
            trigger = random.choice(triggers)
            first = random.choice(all_first_actions)
            second = random.choice(actions_2)

            text = f"{trigger}, {first}, {second}"

            if random.random() < 0.45:
                text += f" {random.choice(extra_layers)}"

            text += random.choice(endings)

            if text not in recent_prescripts:
                break

    recent_prescripts.append(text)

    if len(recent_prescripts) > 50:
        recent_prescripts.pop(0)

    reward = random.randint(8, 20) # Rewards are generally higher than punishments to encourage engagement, but they can be adjusted based on desired difficulty and player experience.
    punishment = random.randint(5, 15) # Punishments are slightly lower on average to avoid discouraging players, but they can be increased if you want to create a more challenging environment.

    return text, reward, punishment