# Generated by Django 6.0.3 on 2026-03-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('total_rewards', models.IntegerField(default=0)),
                ('total_punishments', models.IntegerField(default=0)),
            ],
        ),
    ]
