# Generated by Django 6.0.3 on 2026-03-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescript_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='grace',
            field=models.IntegerField(default=0),
        ),
    ]
