# Generated by Django 6.1 on 2026-08-26 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescript_app', '0002_userprofile_grace'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('action', models.CharField(choices=[('completed', 'Completed'), ('ignored', 'Ignored')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='prescript_app.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
