# Generated by Django 6.1 on 2026-08-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescript_app', '0005_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingnotification',
            name='source',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('requested', 'Requested')], default='requested', max_length=16),
        ),
    ]
