# Generated by Django 6.1 on 2026-08-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescript_app', '0006_pendingnotification_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accepting_prescripts',
            field=models.BooleanField(default=True),
        ),
    ]
